name: vault-demo

services:
  vault:
    image: hashicorp/vault:latest
    container_name: hashicorp-vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-only-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://127.0.0.1:8200
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-root-token-id=dev-only-token
    volumes:
      - vault-data:/vault/data
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  vault-data: